import "server-only";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { createEmbeddedDbFromCsv } from "./embedded-loader";

declare global {
  var flowlensEmbeddedDb: Promise<PGlite> | undefined;
}

// Literal paths (matching EMBEDDED_DATA_DIR/EMBEDDED_FILES) keep Next's file tracing from
// pulling the whole project directory into the function bundle.
const MAIN_DASHBOARD_PATH = path.join(process.cwd(), "data/embedded/main_dashboard.csv.gz");
const FLOW_SUMMARY_PATH = path.join(process.cwd(), "data/embedded/flow_summary.csv.gz");
// Prebuilt Postgres data directory, generated by `pnpm build` (scripts/build-embedded-pgdata.ts).
// Loading it skips initdb, COPY and indexing, which dominate cold starts on Vercel.
const PGDATA_PATH = path.join(process.cwd(), "data/embedded/pgdata.tar.gz");

async function createEmbeddedDb() {
  const startedAt = Date.now();
  const prebuilt = existsSync(PGDATA_PATH);
  const db = prebuilt
    ? await PGlite.create({ loadDataDir: new Blob([readFileSync(PGDATA_PATH)]) })
    : await createEmbeddedDbFromCsv({ mainDashboard: MAIN_DASHBOARD_PATH, flowSummary: FLOW_SUMMARY_PATH });
  console.info(
    `[flowlens] embedded analytics database ready in ${Date.now() - startedAt}ms (${prebuilt ? "prebuilt" : "csv"})`
  );
  return db;
}

export function getEmbeddedDb() {
  globalThis.flowlensEmbeddedDb ??= createEmbeddedDb().catch((error) => {
    globalThis.flowlensEmbeddedDb = undefined;
    throw error;
  });
  return globalThis.flowlensEmbeddedDb;
}
